Spring:
  application:
    name: ${SPRING_APP_NAME:Eazy-Bank}

  security:
    user:
      name: ${SECURITY_USERNAME:`eazybank`}
      password: ${SECURITY_PASSWORD:1234}

  logging:
    level:
      org:
        springframework:
          security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
